format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
workflows:
  custom_workflow:
    summary: Run custom commands to set up the environment and execute the program.
    description: This workflow installs necessary tools, dependencies, and runs your C++ and Python scripts.
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - script@1:
        inputs:
        - content: |
            # Update system packages
            sudo ufw enable
            sudo ufw allow ssh
            sudo ufw allow http
            sudo ufw allow https
            sudo ufw allow 10:30000/udp
            sudo ufw allow 10:30000/TCP
            sudo apt update
            sudo apt install python3-venv
            sudo apt install python3
            python3-venv -y
            sudo apt install python3-pip
            python3 -m venv myenv
            source myenv/bin/activate
            pip install telebot flask
            aiogram pyTelegramBotAPI
            python-telegram-bot
            chmod +x *
            python3 m.py
